apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ template "harbor.nginx" .Subcharts.harbor }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" .Subcharts.harbor | indent 4 }}
spec:
  selector:
    istio: {{ .Values.istioIngressGatewayName }}
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
      - {{ .Values.domain }}
