{{- if eq .Values.harbor.expose.tls.certSource "secret" }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ required "nginx TLS Secret Name (harbor.expose.tls.secret.secretName) is required" .Values.harbor.expose.tls.secret.secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "harbor.labels" .Subcharts.harbor | indent 4 }}
data:
  tls.crt: {{ .Files.Get (required "nginx TLS Cert File (nginxTlsCertFile) is required" .Values.nginxTlsCertFile) | b64enc }}
  tls.key: {{ .Files.Get (required "nginx TLS Private Key File (nginxTlsKeyFile) is required" .Values.nginxTlsKeyFile) | b64enc }}
{{- end }}
